import type { Metadata } from 'next'
import Header from '@/components/shared/header/header'
import Footer from '@/components/shared/footer/footer'


export const metadata: Metadata = {
  title: 'Comfoderm Articles',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  )
}
