import { Metadata, ResolvingMetadata } from 'next'
import styles from './page.module.scss'

type Props = {
  params: { slug: string }
}
export async function generateMetadata(
  { params }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  return {
    title: `Article ${params.slug}`,
    description: 'Generated by create next app',
  }
}

export default function Articles({ params }: { params: { slug: string } }) {
  return <main className={styles.articles_page}>Hello {params.slug}</main>
}
